name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - gpxpy
  - pandas
  - matplotlib
  - geopy
  - mplleaflet
  - pillow
  - tqdm
  - FFmpeg
  - pip
  - pip:
    - trackanimation
    - smopy
